### ISSUE TITLE
电梯直达功能失效

### ISSUE THREAD

**Issue by fiyeck** [mianxiu/Keylol-Style#6]
例如[这个链接](https://keylol.com/forum.php?mod=viewthread&tid=594988&page=1#pid11633853)是跳转到 6 楼的，现在并不会跳转，应该是跟修改了页面结构有关，可以等页面重新渲染完成后通过 `scrollIntoView()` 实现跳转。

**Comment by mianxiu** [comment]
缺少锚点所致，为.post-top添加id="pidXXXXX"后修复
